Add requirements.txt
If this file doesn't exist, `make build` command raises an error:

```
$ make build
sam build --use-container
2019-05-24 15:46:36 Starting Build inside a container
2019-05-24 15:46:37 Building resource 'CertUpdater'

Fetching lambci/lambda:build-python3.6 Docker container image......
2019-05-24 15:46:39 Mounting /Users/moznion/.ghq/github.com/moznion/CertUpdater/src as /tmp/samcli/source:ro,delegated inside runtime container

Build Failed
Running PythonPipBuilder:ResolveDependencies
Running PythonPipBuilder:CopySource
Error: PythonPipBuilder:CopySource - [Errno 2] No such file or directory: '/tmp/samcli/source/requirements.txt'
make: *** [build] Error 1
```

So this commit introduces the file into the project to make the build phase work certainly.